---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: dingotiles/dingo-redis-pivotaltile-pipeline

inputs:
  - name: tile

params:
  opsmgr_url:
  opsmgr_skip_ssl_verification:
  opsmgr_username:
  opsmgr_password:
  opsmgr_ignore_warnings:

run:
  path: tile/ci/tasks/apply-changes.sh
