---
platform: linux
image_resource:
   type: docker-image
   source: {repository: dingotiles/dingo-secrets-pivotaltile-pipeline}

inputs:
- name: tile
- name: tile-version
- name: vault-boshrelease
  path: vault
- name: broker-registrar

outputs:
- name: product

run:
  path: tile/ci/tasks/generate-product.sh
