---
platform: linux
image_resource:
   type: docker-image
   source: {repository: dingotiles/dingo-redis-pivotaltile-pipeline}

inputs:
- name: tile
- name: tile-version
- name: docker-boshrelease
  path: docker
- name: cf-subway-boshrelease
  path: cf-subway
- name: pivnet-stemcell

outputs:
- name: product

run:
  path: tile/ci/tasks/generate-product.sh
