---
platform: linux
image_resource:
   type: docker-image
   source: {repository: dingotiles/dingo-prometheus-pivotaltile-pipeline}

inputs:
- name: tile
- name: tile-version
- name: prometheus-boshrelease
  path: prometheus
- name: node-exporter-boshrelease
  path: node-exporter
- name: pivnet-stemcell

outputs:
- name: product

run:
  path: tile/ci/tasks/generate-product.sh
