---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: dingotiles/dingo-redis-pivotaltile-pipeline

inputs:
  - name: tile
  - name: tile-version

params:
  product_name:
  AWS_ACCESS_KEY_ID:
  AWS_SECRET_ACCESS_KEY:
  AWS_DEFAULT_REGION:
  from_bucket:
  to_bucket:

run:
  path: tile/ci/tasks/promote-public.sh
