---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: dingotiles/dingo-redis-pivotaltile-pipeline

inputs:
  - name: tile
  - name: generated-tile

params:
  product_name:
  opsmgr_url:
  opsmgr_skip_ssl_verification:
  opsmgr_username:
  opsmgr_password:

run:
  path: tile/ci/tasks/upload-product.sh
