---
platform: linux
image: docker:///dingotiles/dingo-prometheus-pivotaltile-pipeline

inputs:
- name: tile
- name: pivnet-stemcell

params:
  opsmgr_url:
  opsmgr_skip_ssl_verification:
  opsmgr_username:
  opsmgr_password:
  opsmgr_version:

run:
  path: tile/ci/tasks/upload-stemcell.sh
