---
groups:
- name: pipeline
  jobs:
  - create-product
  # - shipit
  - patch
  - minor
  - major
  # - promote
- name: stemcells
  jobs: [upload-stemcell]
- name: image
  jobs: [build-task-image]

jobs:
- name: upload-stemcell
  plan:
  - aggregate:
    - get: tile
    - get: pivnet-stemcell
      trigger: true
      params: {globs: ["*vsphere*"]}
  - aggregate:
    - task: upload-stemcell-opsmgr110
      file: tile/ci/tasks/upload-stemcell.yml
      params:
        opsmgr_url: {{opsmgr110-url}}
        opsmgr_skip_ssl_verification: {{opsmgr110-skip-ssl-verification}}
        opsmgr_username: {{opsmgr110-username}}
        opsmgr_password: {{opsmgr110-password}}
        opsmgr_version: 1.7

- name: create-product
  serial_groups: [opsmgr110]
  plan:
  - aggregate:
    - get: tile
    - get: product-tile
      # trigger: true
    - get: docker-boshrelease
      # trigger: true
      params: {tarball: true}
    - get: cf-subway-boshrelease
      params: {tarball: true}
    - get: broker-registrar-boshrelease
      params: {tarball: true}
    - get: pivnet-stemcell
      params: {globs: ["*vsphere*"]}
      # trigger: true
      # passed: [upload-stemcell]
    - get: tile-version
      params: {pre: rc}
  - task: generate-product
    file: tile/ci/tasks/generate-product.yml
    params:
      AWS_ACCESS_KEY: {{concourse-aws-access-key}}
      AWS_SECRET_KEY: {{concourse-aws-secret-access-key}}
  - put: generated-tile
    params: {file: product/dingo-redis-*.pivotal}
  - put: tile-version
    params: {file: tile-version/number}
  - task: upload-product-opsmgr110
    file: tile/ci/tasks/upload-product.yml
    params:
      opsmgr_url: {{opsmgr110-url}}
      opsmgr_skip_ssl_verification: {{opsmgr110-skip-ssl-verification}}
      opsmgr_username: {{opsmgr110-username}}
      opsmgr_password: {{opsmgr110-password}}
      opsmgr_version: 1.7

# - name: shipit
#   serial_groups: [opsmgr16, opsmgr110]
#   plan:
#   - aggregate:
#     - { get: tile }
#     - { get: generated-tile, passed: [create-product] }
#     - { get: tile-version,   passed: [create-product], params: { bump: final } }
#   - task: re-version-product
#     file: tile/ci/tasks/re-version-product.yml
#     params:
#       AWS_ACCESS_KEY: {{concourse-aws-access-key}}
#       AWS_SECRET_KEY: {{concourse-aws-secret-access-key}}
#   - put: tile-version
#     params: {file: tile-version/number}
#   - put: generated-tile
#     params: {file: reversioned-product/dingo-redis-*.pivotal}
#   - aggregate:
#     - task: upload-product-opsmgr110
#       file: tile/ci/tasks/upload-product.yml
#       params:
#         opsmgr_url: {{opsmgr110-url}}
#         opsmgr_skip_ssl_verification: {{opsmgr110-skip-ssl-verification}}
#         opsmgr_username: {{opsmgr110-username}}
#         opsmgr_password: {{opsmgr110-password}}
#         opsmgr_version: 1.7
#

- name: patch
  public: true
  plan:
  # - { get: tile-version, passed: [shipit], trigger: true, params: { bump: patch, pre: rc } }
  - { get: tile-version, trigger: true, params: { bump: patch, pre: rc } }
  - { put: tile-version, params: { file: tile-version/number } }

- name: major
  public: true
  plan:
  - get: tile-version
    params: {bump: major, pre: rc}
  - put: tile-version
    params: {file: tile-version/number}

- name: minor
  public: true
  plan:
  - get: tile-version
    params: {bump: minor, pre: rc}
  - put: tile-version
    params: {file: tile-version/number}


- name: build-task-image
  serial: true
  plan:
  - get: docker-image-tile
    trigger: true
  - put: docker-image
    params:
      build: docker-image-tile/ci/ci_image

resources:
- name: tile
  type: git
  source:
    uri: git@github.com:dingotiles/dingo-redis-pivotaltile.git
    branch: {{tile-branch}}
    private_key: {{github-key}}
- name: product-tile
  type: git
  source:
    uri: git@github.com:dingotiles/dingo-redis-pivotaltile.git
    branch: {{tile-branch}}
    private_key: {{github-key}}
    paths: [templates]
- name: docker-image-tile
  type: git
  source:
    uri: git@github.com:dingotiles/dingo-redis-pivotaltile.git
    branch: {{tile-branch}}
    private_key: {{github-key}}
    paths: [ci/ci_image/*]
- name: docker-image
  type: docker-image
  source:
    email: {{docker-hub-email}}
    username: {{docker-hub-username}}
    password: {{docker-hub-password}}
    repository: dingotiles/dingo-redis-pivotaltile-pipeline

- name: tile-version
  type: semver
  source:
    driver: git
    uri: git@github.com:dingotiles/dingo-redis-pivotaltile.git
    branch: version
    file: version
    initial_version: 0.0.1
    private_key: {{github-key}}

- name: docker-boshrelease
  type: github-release
  source:
    access_token: {{github-release-access-token}}
    user: cloudfoundry-community
    repository: docker-boshrelease
    pre_release: true

- name: cf-subway-boshrelease
  type: bosh-io-release
  source:
    repository: cloudfoundry-community/cf-subway-boshrelease

- name: broker-registrar-boshrelease
  type: bosh-io-release
  source:
    repository: cloudfoundry-community/broker-registrar-boshrelease

- name: pivnet-stemcell
  type: pivnet
  source:
    api_token: {{pivnet-api-token}}
    product_slug: stemcells
    product_version: 3363\..*

- name: generated-tile
  type: s3
  source:
    access_key_id: {{concourse-aws-access-key}}
    secret_access_key: {{concourse-aws-secret-access-key}}
    bucket: dingo-redis-pivotaltile
    regexp: dingo-redis-(.*).pivotal
    region_name: ap-southeast-1

resource_types:
- name: pivnet
  type: docker-image
  source:
    repository: pivotalcf/pivnet-resource
    tag: latest-final
